# tasks file for ubuntu-1604-collectd-haproxy
---
- name: create directory
  file:
    path: "{{ ubuntu_1604_collectd_haproxy_install_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: download and install
  get_url:
    url: "{{ ubuntu_1604_collectd_haproxy_download_url }}/raw/{{ ubuntu_1604_collectd_haproxy_version }}/haproxy.py"
    dest: "{{ ubuntu_1604_collectd_haproxy_install_path }}/haproxy.py"
    owner: root
    group: root
    mode: 0644
    force: true
    timeout: 60

- name: enable and configure plugin
  template:
    src: "etc/collectd/collectd.conf.d/haproxy.conf.j2"
    dest: "/etc/collectd/collectd.conf.d/haproxy.conf"
  notify: restart collectd
